# Generated by Django 5.2.4 on 2026-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
